spring:
  application:
    name: finance

  datasource:
    url: jdbc:mysql://localhost:3306/finance
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver

    flyway:
      enabled: true
      baseline-on-migrate: true
      baseline-version: 2
      repair-on-migrate: true

brapi:
  url: https://brapi.dev/api
  token: ${BRAPI_TOKEN}