spring:
  application:
    name: finance

  datasource:
    url: jdbc:mysql://localhost:3306/finance
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver

    flyway:
      enabled: true
      baseline-on-migrate: true
      baseline-version: 2
      repair-on-migrate: true

  data:
    redis:
      host: localhost
      port: 6379

brapi:
  url: https://brapi.dev/api
  token: ${BRAPI_TOKEN}

cloudconvert:
  url: https://api.cloudconvert.com
  token: ${CLOUDCONVERT_TOKEN}

anbima:
  base-url: https://www.anbima.com.br
  url: https://www.anbima.com.br/feriados/arqs/feriados_nacionais.xls

bcb:
  base-url-odata: https://olinda.bcb.gov.br/olinda/servico/IFDATA/versao/v1/odata

b3:
  base-url: https://cotacao.b3.com.br

resilience4j:
  circuitbreaker:
    instances:
      brapi-circuit-breaker:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        minimumNumberOfCalls: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true

storage:
  local:
    location: "./local-bucket"