spring:
  application:
    name: finance

  datasource:
    url: jdbc:mysql://localhost:3306/finance
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver

    flyway:
      enabled: true
      baseline-on-migrate: true
      baseline-version: 2
      repair-on-migrate: true

brapi:
  url: https://brapi.dev/api
  token: ${BRAPI_TOKEN}

cloudconvert:
  url: https://api.cloudconvert.com
  token: ${CLOUDCONVERT_TOKEN}

anbima:
  url: https://www.anbima.com.br/feriados/arqs/feriados_nacionais.xls

resilience4j:
  circuitbreaker:
    instances:
      brapi-circuit-breaker:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        minimumNumberOfCalls: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true